### ISSUE TITLE
Make an appointment scheduling page

### ISSUE THREAD

**Issue by lukesaleh** [MedTrackSWE/MedTrack#15]
We need a front end page to allow the scheduling of appointments. It will also need to show upcoming appointments, and should have a drop down menu to select a hospital to schedule the appointment at.

**Comment by emmaherrero** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create front end for appointment scheduling](https://trello.com/c/8mHXi3YB/12-create-front-end-for-appointment-scheduling)

**Comment by lukesaleh** [comment]
Closed with PR #25
